### ISSUE TITLE
MD5 mismatch for certain positions

### ISSUE THREAD

**Issue by drramki-chop** [stevenpastor/SVCure#2]
IGV throws a MD5 mismatch error for some positions.

![IGV_MD5_mismatch_error](https://user-images.githubusercontent.com/16145673/83032823-508db900-a004-11ea-9185-a99d9820eab0.png)

**Comment by stevenpastor** [comment]
I am pretty sure this has to do with mismatched reference builds and igvjs looking for a build other than the one the user provided. This could be in some combination of mismatch in the form input, cram (header), and the fasta file. I think in our case, it was an old example cram file, and its header contained hsd37 (it was aligned to hsd37). In the example, I erroneously input the reference as hg38, so it threw an error. I fixed the example loaded data to reflect this.
